### ISSUE TITLE
LWIP installation issues

### ISSUE THREAD

**Issue by madisonmay** [IndicoDataSolutions/IndicoIo-node#67]
The lwip package is prone to installation issues, should see what we can do to remedy it on our end.

**Comment by JoseRoman** [comment]
This should be fixed once LWIP migrates NAN to 2.0 which is what Node 4.0.0 uses. There is currently an open [PR](https://github.com/EyalAr/lwip/pull/182)  to fix this in the LWIP repo.

**Comment by sihrc** [comment]
Awesome. Thanks for letting us know @JoseRoman

**Comment by JoseRoman** [comment]
@madisonmay, @sihrc this issue should be fixed with the new version of LWIP 0.0.8.

**Comment by sihrc** [comment]
@JoseRoman  Awesome, thank you!

**Comment by meticulo3366** [comment]
Is this the issue that I am running into?

s4_1        | Error: Cannot find module '../build/Release/lwip_image'
s4_1        |     at Function.Module._resolveFilename (module.js:337:15)
s4_1        |     at Function.Module._load (module.js:287:25)
s4_1        |     at Module.require (module.js:366:17)
s4_1        |     at require (module.js:385:17)
s4_1        |     at /code/node_modules/indico.io/node_modules/lwip/lib/Image.js:3:22
s4_1        |     at Object.<anonymous> (/code/node_modules/indico.io/node_modules/lwip/lib/Image.js:16:3)
s4_1        |     at Module._compile (module.js:435:26)
s4_1        |     at Object.Module._extensions..js (module.js:442:10)
s4_1        |     at Module.load (module.js:356:32)
s4_1        |     at Function.Module._load (module.js:311:12)
s4_1        |     at Module.require (module.js:366:17)
s4_1        |     at require (module.js:385:17)
s4_1        |     at /code/node_modules/indico.io/node_modules/lwip/lib/ImagePrototypeInit.js:3:17
s4_1        |     at Object.<anonymous> (/code/node_modules/indico.io/node_modules/lwip/lib/ImagePrototypeInit.js:620:3)
s4_1        |     at Module._compile (module.js:435:26)
s4_1        |     at Object.Module._extensions..js (module.js:442:10)
s4_1        |     at Module.load (module.js:356:32)
s4_1        |     at Function.Module._load (module.js:311:12)
s4_1        |     at Module.require (module.js:366:17)
s4_1        |     at require (module.js:385:17)
s4_1        |     at Object.<anonymous> (/code/node_modules/indico.io/node_modules/lwip/index.js:1:63)
s4_1        |     at Module._compile (module.js:435:26)
s4_1        |     at Object.Module._extensions..js (module.js:442:10)
s4_1        |     at Module.load (module.js:356:32)
s4_1        |     at Function.Module._load (module.js:311:12)
s4_1        |     at Module.require (module.js:366:17)
s4_1        |     at require (module.js:385:17)
s4_1        |     at Object.<anonymous> (/code/node_modules/indico.io/lib/image.js:1:74)

package.json below...


{
  "name": "indico.io",
  "description": "A Node.js wrapper for the Indico’s API",
  "version": "0.4.6",
  "homepage": "https://github.com/IndicoDataSolutions/IndicoIo-node",
  "author": {
    "name": "Joseph Núñez",
    "email": "toctochello@gmail.com"
  },
  "contributors": [
    {
      "name": "Madison May",
      "email": "madison@indico.io"
    }
  ],
  "keywords": [],
  "repository": {
    "type": "git",
    "url": "git://github.com/IndicoDataSolutions/IndicoIo-node.git"
  },
  "bugs": {
    "url": "https://github.com/IndicoDataSolutions/IndicoIo-node/issues"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/IndicoDataSolutions/IndicoIo-node/blob/master/LICENSE"
    }
  ],
  "main": "./lib/indico",
  "dependencies": {
    "bluebird": "^2.9.24",
    "config-ini": "^0.2.2",
    "expand-tilde": "^1.2.0",
    "file-type": "^2.11.0",
    "lwip": "0.0.8",
    "request": "^2.36.0",
    "valid-url": "^1.0.9"
  },
  "devDependencies": {
    "should": "~3.0.1",
    "mocha": "~1.17.0",
    "chai": "1.9.1"
  },
  "scripts": {
    "test": "mocha test/*.js test/integration/*.js"
  },
  "js-flags": "--harmony",
  "_id": "indico.io@0.4.6",
  "_shasum": "f6fb1d899427bfe50803b9580b1f8d89935c73be",
  "_resolved": "https://registry.npmjs.org/indico.io/-/indico.io-0.4.6.tgz",
  "_from": "indico.io@>=0.4.6 <0.5.0",
  "_npmVersion": "2.11.2",
  "_nodeVersion": "4.2.0",
  "_npmUser": {
    "name": "madisonmay",
    "email": "madison@indico.io"
  },
  "dist": {
    "shasum": "f6fb1d899427bfe50803b9580b1f8d89935c73be",
    "tarball": "http://registry.npmjs.org/indico.io/-/indico.io-0.4.6.tgz"
  },
  "maintainers": [
    {
      "name": "slatervictoroff",
      "email": "slater@indico.io"
    },
    {
      "name": "madisonmay",
      "email": "madison@indico.io"
    },
    {
      "name": "indicodatasolutions",
      "email": "contact@indico.io"
    }
  ],
  "directories": {}
}

**Comment by meticulo3366** [comment]
perhaps we can use a precompiled binary option?

https://github.com/EyalAr/lwip/issues/83

**Comment by xraywu** [comment]
And it is especially difficult to deploy this on AWS Lambda due to lwip compiling/installation issues...

**Comment by pondre-brandon** [comment]
+1 for Google Could Compute instances as well.

**Comment by Didericis** [comment]
I've created a [fork](https://github.com/PatientWisdom/IndicoIo-node-text) of this that removes all the image processing, as we didn't need it in our current project and were having installation issues. Could this be broken up into a separate `indico.io-text` and `indico.io-image` package that the main `indico.io` package references?

**Comment by suissemaxx** [comment]
Same error here. I am unable to install. The lwip package throws a build error. Any news, when this can be fixed?

```
3 warnings and 4 errors generated.
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error 
```

**Comment by sihrc** [comment]
LWIP is currently an *optional* dependency. If you are not working with images, a current workaround would be to install the package without the optional dependencies. http://unix.stackexchange.com/a/256960

**Comment by sihrc** [comment]
@suissemaxx Could you post a little bit more of your stack trace please?

**Comment by sihrc** [comment]
I believe I've reproduced the error with:
node -> v6.8.1
npm -> 3.3.8

A new 0.10.4 indico.io package has been deployed in #123 that updates the LWIP dependency which fixes the error that was reproduced.

**Comment by sihrc** [comment]
We'll leave this issue open until a more sustainable solution is implemented. Until then, if anyone begins to have issues with LWIP installation again, we will again update the lib as necessary.
